export default {
    BASE_URL: 'http://da.clientdemo.club/api',
    // BASE_URL: 'http://192.168.1.2:4000/api',
    COLORS: {
        THEME_COLOR: '#3FB9FF',
        WHITE: '#FFF',
        FONT_BLACK: '#333',
        INACTIVE_COLOR: '#C1C1C1',
        UNDERLAY_COLOR: '#EEE'
    },
    APIS: {
        LOGIN: '/login',
        REGISTER: '/register',
        SAVE_PRESCRIPTION: '/add_prescription',
        GET_DOCTOR_LIST: '/get_doctor_list',
        GET_DRUGS: '/DrugBrands',
        GET_DRUG: '/DrugBrands/:id',
        GET_INDICATIONS: '/Indications',
        GET_PRESCRIPTION_BY_DOCTOR: '/get_prescriptions',
        UPDATE_PROFILE_META: '/update_profile_meta',
        GET_PRESCRIPTION_BY_PATIENT: '/get_prescriptions_patient',
        GET_CURRENT_QUEUE: '/get_current_queue',
        UPDATE_DOCTOR_STATUS: '/update_doctor_status',
        GET_NEXT_PATIENT: '/get_next_patient',
        UPDATE_PATIENT_QUEUUE: '/update_patient_queue',
        UPDATE_APPOINTMENT_QUEUE: '/update_appointment_queue',
        GET_DOCTORS_SPECIALITIES: '/get_speciality_names',
        GET_PATIENTS_BY_DR: '/get_patients_by_doctor_id',
        SCHEDULE_UPDATE: '/update_schedule',
        SCHEDULE_UPDATE_TIME: '/update_schedule_time',
        GET_PATIENT_OTHER_HISTORY: '/get_other_profile_history',
        UPDATE_DOCTOR: '/update_doctor',
    },
    PROFILE_PIC_BASE: 'http://da.clientdemo.club/profiles/',
    DATA: {
        SENDER_ID: '874421273888'
    },
    TIMES_LIST: [
        "08:00 AM",
        "08:30 AM",
        "09:00 AM",
        "09:30 AM",
        "10:00 AM",
        "10:30 AM",
        "11:00 AM",
        "11:30 AM",
        "12:00 PM",
        "12:30 PM",
        "01:00 PM",
        "01:30 PM",
        "02:00 PM",
        "02:30 PM",
        "03:00 PM",
        "03:30 PM",
        "04:00 PM",
        "04:30 PM",
        "05:00 PM",
        "05:30 PM",
        "06:00 PM",
        "06:30 PM",
        "07:00 PM",
        "07:30 PM",
        "08:00 PM",
        "08:30 PM",
        "09:00 PM",
        "09:30 PM",
        "10:00 PM",
        "10:30 PM",
        "11:00 PM",
        "11:30 PM",
        "12:00 AM"
    ]
}