import React from 'react';
import { View, TouchableHighlight, Text, StyleSheet, Image } from 'react-native';
import { PermissionsAndroid } from 'react-native';
// import PushNotification from 'react-native-push-notification';

import Entypo from 'react-native-vector-icons/Entypo';

import CONST from '../lib/constants';
import API from '../lib/api';
import splash_screen_img from '../assets/splash_screen_img.png';



export default class FirstPage extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            // emailAddr: '',
            // password: '',
            userInfo: null,
            pushToken: ''
        }
        this.API = new API();

    }

    async componentDidMount() {

        const userInfo = await this.API._retrieveData('userInfo');
        // console.log('user Info from FirstPage: ', userInfo)
        const pushToken = await this.API._retrieveData('pushToken');
        console.log('Stored Token: ',pushToken);
        if (pushToken !== '') {
            this.setState({
                pushToken
            })
        }
        
        if(userInfo !== null) {
            this.setState({ userInfo });
            this.props.navigation.navigate('Home');
        }

        // BackHandler.addEventListener('hardwareBackPress', () => {

        //     if (routeName === 'firstPage') {
        //         console.log('Back Button Pressed');

        //         // return true;
        //         // BackHandler.exitApp();
        //     }
        //     return true;

        // });

        


    }

    // EnablePushToken = () => {
    //     var newThis = this;

    //     if (this.state.pushToken !== '') {

    //         PushNotification.configure({

    //             // (optional) Called when Token is generated (iOS and Android)
    //             onRegister: async function (token) {
    //                 console.log('TOKEN:', token);
    //                 await newThis.API._storeData('pushToken', token.token);
    //             },

    //             // (required) Called when a remote or local notification is opened or received
    //             onNotification: function (notification) {
    //                 console.log('NOTIFICATION:', notification);

    //                 // alert(notification.message);
    //                 // process the notification

    //                 // PushNotification.localNotification({
    //                 //     /* Android Only Properties */
    //                 //     id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
    //                 //     ticker: "My Notification Ticker", // (optional)
    //                 //     autoCancel: true, // (optional) default: true
    //                 //     largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
    //                 //     smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
    //                 //     bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
    //                 //     subText: "This is a subText", // (optional) default: none
    //                 //     color: "red", // (optional) default: system default
    //                 //     vibrate: true, // (optional) default: true
    //                 //     vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
    //                 //     ongoing: true, // (optional) set whether this is an "ongoing" notification
    //                 //     priority: "high", // (optional) set notification priority, default: high
    //                 //     visibility: "private", // (optional) set notification visibility, default: private
    //                 //     importance: "high", // (optional) set notification importance, default: high


    //                 //     /* iOS and Android properties */
    //                 //     title: "My Local Notification Title", // (optional)
    //                 //     message: "My Local Notification Messages..", // (required)
    //                 //     playSound: true, // (optional) default: true
    //                 //     number: '10', // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
    //                 //     repeatType: 'day', // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
    //                 //     repeatTime: 22222223, // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
    //                 //     importance: 'high', // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
    //                 // });
    //             },

    //             senderID: CONST.DATA.SENDER_ID,

    //             // IOS ONLY (optional): default: all - Permissions to register.
    //             permissions: {
    //                 alert: true,
    //                 badge: true,
    //                 sound: true
    //             },

    //             // Should the initial notification be popped automatically
    //             // default: true
    //             popInitialNotification: true,

    //             /**
    //               * (optional) default: true
    //               * - Specified if permissions (ios) and token (android and ios) will requested or not,
    //               * - if not, you must call PushNotificationsHandler.requestPermissions() later
    //               */
    //             requestPermissions: true,
    //         });
    //     }


    // }

    registerDeviceAndPush = async () => {

        const getPermission = await PermissionsAndroid.requestMultiple([
            PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
            PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
            PermissionsAndroid.PERMISSIONS.CAMERA,
        ]);

        var ifPermissionDenied = true;
        for (var permission in getPermission) {
            if (getPermission[permission] != 'granted') {
                ifPermissionDenied = false;
            }
        }

        console.log(getPermission);
        return ifPermissionDenied;
    }


    goForRegistration = async() => {

        if (this.registerDeviceAndPush()) {

            this.props.navigation.navigate("LoginPage");
        } else {
            alert("You must need to enable this permission to continue");
        }
        // return false;

        
    }

    render() {
        

        return (
            <View style={{ flex: 1, flexDirection: 'column' }}>
                <View style={{
                    flex: .08,
                    backgroundColor: '#008FC1',
                    alignItems: 'center',
                }}>
                </View>
                <View style={{ flex: .92, backgroundColor: CONST.COLORS.THEME_COLOR}}>
                    <View style={{
                        flex: .60,
                        alignItems: 'center',
                        marginTop: 60,
                    }}>
                        <Image source={splash_screen_img} style={{}} />
                    </View>
                    <View style={{flex: .20, alignItems: 'center'}}>
                        <Text style={styles.txtStyleDoctor}>
                            Best online assistant app for Doctors
                        </Text>
                    </View>
                    <View style={{flex: .20}}> 
                        <TouchableHighlight style={styles.fbBtnWrapper} underlayColor="transparent" onPress={this.goForRegistration}>
                            <View style={styles.subBtnView}>
                                <Text style={{ color: '#355C95', marginTop: 5}}>SIGN UP WITH</Text>
                                <Entypo name="old-mobile" size={30} color='#355C95'/>
                            </View>
                        </TouchableHighlight>
                    </View>
                </View>
            </View>
        )
    }
}

const styles = StyleSheet.create({
    inputItem: { 
        flexDirection: 'column',
        flex: .5, 
        marginRight: 13
    },
    inputItemFull: { 
        flexDirection: 'column',
        flex: 1, 
        marginRight: 13
    },
    inputItemTitle: { 
        color: '#AEAFB1',
        fontWeight: '400',
        marginBottom: 10
    },
    inputItemText: {
        borderColor: '#EEEEEE', 
        borderWidth: 2, 
        padding: 4,
        paddingLeft: 8,
        fontSize: 12, 
        borderRadius: 5 
    },
    inputFieldsWrapper: {
        flexDirection: 'row', 
        marginTop: 30 
    },

    fbBtnWrapper: { 
        backgroundColor: '#FFFFFF', 
        elevation: 4, 
        borderRadius: 30, 
        marginLeft: 50, 
        marginRight: 50 
    },
    subBtnView: { 
        flexDirection: 'row', 
        paddingTop: 6, 
        paddingBottom: 6, 
        paddingLeft: 25, 
        paddingRight: 10 ,
        alignSelf: 'center'
    },
    txtStyleDoctor: { 
        fontSize: 20, 
        fontWeight: 'bold', 
        color: '#FFF', 
        paddingLeft: 60, 
        paddingRight: 60, 
        textAlign: 'center' 
    },



})